services:
  mcp-server:
    build: .
    container_name: mcp_server_rag
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./mis_notas:/app/mis_notas
    command: python server.py
    restart: always

  indexer:
    build: .
    container_name: mcp_indexer_rag
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./documentos:/app/documentos
    command: python indexador_pro.py
    restart: always